services:
  - type: web
    name: quizzq2
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: quizzq2
          property: host
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
